FROM ubuntu:latest
#FROM homeassistant/amd64-base:latest
#FROM resin/rpi-raspbian
ENV LANG C.UTF-8

WORKDIR /data

#ONBUILD RUN apt-get update && apt-get upgrade -y && apt-get install -y screen

RUN apt-get update && apt-get upgrade -y && apt-get install -y apt-utils && apt-get install -y vim screen
COPY ngrokd /etc/init.d/
RUN chmod a+x /etc/init.d/ngrokd
RUN mkdir .ngrok2
COPY ngrok.yml .ngrok2/
COPY ngrok-amd64 /root/ngrok
#RUN screen -d -m /root/ngrok start -all -config /data/.ngrok2/ngrok.yml

COPY run.sh /
RUN chmod a+x /run.sh

CMD [ "/run.sh" ]


# docker image build -f .\Dockerfile-amd64 -t local:ff
# docker container run -it --name ff local:ff /bin/bash
